version: '3.2'
services:
  app:
    build: .
    ports:
      - 8084:80
    volumes:
      - ./:/var/www:rw
  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306    
    environment:
      MYSQL_ROOT_PASSWORD: admin

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
